@startuml
'https://plantuml.com/class-diagram



GeneralPage <|-- MainPage
MainPage <|-- LoginUser
GeneralPage <|-- UserRegistration
LoginUser <|-- UserPage

TestMain *-- MainPage
TestRegistration *-- UserRegistration
TestLoginLogout *-- LoginUser
TestUserActions  *-- UserPage
class GeneralPage{
browser
url
open()
close()
refresh()
save_screen(path)
}

cLass ConduitDatabase{

}
@enduml